
import type { ExerciseData, MuscleGroup } from '@/types';

// Default exercises - ID will be generated by Firestore
export const defaultExercises: ExerciseData[] = [
  // Chest
  { name: "Incline chest w/dumbbells", muscleGroup: "Chest", description: "Targets upper chest.", dataAiHint: "dumbbell press" },
  { name: "Incline chest w/ Smith Machine", muscleGroup: "Chest", description: "Targets upper chest using a Smith machine.", dataAiHint: "smith machine" },
  { name: "Machine Chest Press", muscleGroup: "Chest", description: "Targets middle chest using a machine.", dataAiHint: "chest machine" },
  { name: "Bench Press", muscleGroup: "Chest", description: "Compound movement for middle chest.", dataAiHint: "bench press" },
  { name: "Seated Cable Pec Flye", muscleGroup: "Chest", description: "Isolation exercise for lower chest using cables.", dataAiHint: "cable fly" },
  { name: "Dips", muscleGroup: "Chest", description: "Compound bodyweight exercise targeting lower chest and triceps.", dataAiHint: "dips fitness" },

  // Back
  { name: "Wide-Grip Pull ups", muscleGroup: "Back", description: "Targets lats and middle back.", dataAiHint: "pull up" },
  { name: "Chest-Supported Row", muscleGroup: "Back", description: "Targets upper and middle back, reduces lower back strain.", dataAiHint: "row machine" },
  { name: "Wide-Grip Lat Pull down", muscleGroup: "Back", description: "Targets lats and middle back using a machine.", dataAiHint: "lat pulldown" },
  { name: "Neutral-Grip Lat Pull down", muscleGroup: "Back", description: "Targets lats and teres major with a neutral grip.", dataAiHint: "lat pulldown" },
  { name: "Half-Kneeling 1-Arm Lat Pulldown", muscleGroup: "Back", description: "Unilateral exercise targeting lats and teres major.", dataAiHint: "lat pulldown cable" },
  { name: "Barbell Rows", muscleGroup: "Back", description: "Compound movement for upper and middle back.", dataAiHint: "barbell row" },

  // Shoulders
  { name: "Standing Overhead Press", muscleGroup: "Shoulders", description: "Targets anterior deltoid.", dataAiHint: "overhead press" },
  { name: "Dumbbell Overhead Press", muscleGroup: "Shoulders", description: "Targets anterior deltoid using dumbbells.", dataAiHint: "dumbbell press" },
  { name: "Machine Shoulder Press", muscleGroup: "Shoulders", description: "Targets anterior deltoid using a machine.", dataAiHint: "shoulder machine" },
  { name: "Lateral Raise Machine", muscleGroup: "Shoulders", description: "Targets lateral deltoid using a machine.", dataAiHint: "lateral raise machine" },
  { name: "Lateral Raise Dumbbell", muscleGroup: "Shoulders", description: "Targets lateral deltoid using dumbbells.", dataAiHint: "dumbbell raise" },
  { name: "Cable Lateral Raise", muscleGroup: "Shoulders", description: "Targets lateral deltoid using cables.", dataAiHint: "cable raise" },
  { name: "Reverse Peck Deck", muscleGroup: "Shoulders", description: "Targets posterior deltoid using a machine.", dataAiHint: "reverse fly machine" },
  { name: "Seated Reverse Dumbbell Flye", muscleGroup: "Shoulders", description: "Targets posterior deltoid using dumbbells.", dataAiHint: "dumbbell fly" },

  // Legs
  { name: "Barbell Back Squat", muscleGroup: "Legs", description: "Targets quadriceps, glutes, and hamstrings.", dataAiHint: "barbell squat" },
  { name: "Hack Squat", muscleGroup: "Legs", description: "Targets quadriceps using a hack squat machine.", dataAiHint: "hack squat" },
  { name: "Leg Extension", muscleGroup: "Legs", description: "Isolation exercise for quadriceps.", dataAiHint: "leg extension machine" },
  { name: "Leg Press Machine", muscleGroup: "Legs", description: "Targets quadriceps and glutes using a machine.", dataAiHint: "leg press machine" },
  { name: "Leg Curl Machine", muscleGroup: "Legs", description: "Isolation exercise for hamstrings.", dataAiHint: "leg curl machine" },
  { name: "Romanian Dead Lift", muscleGroup: "Legs", description: "Targets hamstrings and glutes.", dataAiHint: "romanian deadlift" },
  { name: "Hip Thrust", muscleGroup: "Legs", description: "Targets glutes.", dataAiHint: "hip thrust exercise" },
  { name: "Abductor Machine", muscleGroup: "Legs", description: "Targets glutes (abductors).", dataAiHint: "abductor machine" },
  { name: "Standing Calves", muscleGroup: "Legs", description: "Targets gastrocnemius (calves).", dataAiHint: "calf raise" },

  // Triceps
  { name: "Dips (Triceps Focus)", muscleGroup: "Triceps", description: "Bodyweight exercise, emphasizing lateral head of triceps.", dataAiHint: "tricep dips" },
  { name: "Cable Triceps Kickback", muscleGroup: "Triceps", description: "Isolation exercise for lateral head using cables.", dataAiHint: "tricep kickback" },
  { name: "Overhead Cable Triceps Extension", muscleGroup: "Triceps", description: "Targets long head of triceps using cables.", dataAiHint: "tricep extension cable" },
  { name: "Skullcrusher", muscleGroup: "Triceps", description: "Targets long head of triceps, typically with an EZ bar or dumbbells.", dataAiHint: "skullcrusher exercise" },

  // Biceps
  { name: "EZ Bar Curl", muscleGroup: "Biceps", description: "Targets short head (inner) of biceps.", dataAiHint: "ez bar curl" },
  { name: "Chinup", muscleGroup: "Biceps", description: "Compound bodyweight exercise targeting biceps (short and long heads) and back.", dataAiHint: "chin up" },
  { name: "Incline Dumbbell Curl", muscleGroup: "Biceps", description: "Targets long head (outer) of biceps.", dataAiHint: "incline curl" },
  { name: "Face Away Bayesian Cable Curl", muscleGroup: "Biceps", description: "Targets long head (outer) of biceps using cables.", dataAiHint: "cable curl" },
  { name: "Hammer Curl", muscleGroup: "Biceps", description: "Targets brachialis and brachioradialis, adding thickness to the arm.", dataAiHint: "hammer curl" },

  // Abs
  { name: "Cable Crunch", muscleGroup: "Abs", description: "Targets upper abs using cables.", dataAiHint: "cable crunch abs" },
  { name: "Crunch Machine", muscleGroup: "Abs", description: "Targets upper abs using a machine.", dataAiHint: "abs machine" },
  { name: "Candlestick", muscleGroup: "Abs", description: "Targets upper and lower abs.", dataAiHint: "candlestick abs" },
  { name: "Hanging Leg Raise", muscleGroup: "Abs", description: "Targets lower abs.", dataAiHint: "leg raise hanging" },
  { name: "Back-Supported Leg Raise", muscleGroup: "Abs", description: "Targets lower abs with back support.", dataAiHint: "leg raise support" },
  { name: "Super Range Motion Crunch", muscleGroup: "Abs", description: "Targets upper and lower abs with extended range of motion.", dataAiHint: "abs crunch" },
  { name: "Abs Wheel/Rollout", muscleGroup: "Abs", description: "Targets core stability.", dataAiHint: "ab wheel" },
  
  // Other (Example, can be expanded)
  { name: "Foam Rolling", muscleGroup: "Other", description: "Myofascial release technique.", dataAiHint: "foam roller" },
  { name: "Stretching", muscleGroup: "Other", description: "General flexibility work.", dataAiHint: "stretching fitness" },
];
