
import type { ExerciseData, MuscleGroup } from '@/types';

// Default exercises - ID will be generated by Firestore
export const defaultExercises: ExerciseData[] = [
  // Chest
  { name: "Incline chest w/dumbbells", muscleGroup: "Chest", targetNotes: "Upper Chest", dataAiHint: "dumbbell press" },
  { name: "Incline chest w/ Smith Machine", muscleGroup: "Chest", targetNotes: "Upper Chest", dataAiHint: "smith machine" },
  { name: "Machine Chest Press", muscleGroup: "Chest", targetNotes: "Middle Chest", dataAiHint: "chest machine" },
  { name: "Bench Press", muscleGroup: "Chest", targetNotes: "Middle Chest", dataAiHint: "bench press" },
  { name: "Seated Cable Pec Flye", muscleGroup: "Chest", targetNotes: "Lower Chest", dataAiHint: "cable fly" },
  { name: "Dips", muscleGroup: "Chest", targetNotes: "Lower Chest", dataAiHint: "dips fitness" },

  // Back
  { name: "Wide-Grip Pull ups", muscleGroup: "Back", targetNotes: "Lats and Middle Back", dataAiHint: "pull up" },
  { name: "Chest-Supported Row", muscleGroup: "Back", targetNotes: "Upper Back and Middle Back", dataAiHint: "row machine" },
  { name: "Wide-Grip Lat Pull down", muscleGroup: "Back", targetNotes: "Lats and Middle Back", dataAiHint: "lat pulldown" },
  { name: "Neutral-Grip Lat Pull down", muscleGroup: "Back", targetNotes: "Lats and Teres Major", dataAiHint: "lat pulldown" },
  { name: "Half-Kneeling 1-Arm Lat Pulldown", muscleGroup: "Back", targetNotes: "Lats and Teres Major", dataAiHint: "lat pulldown cable" },
  { name: "Barbell Rows", muscleGroup: "Back", targetNotes: "Upper Back and Middle Back", dataAiHint: "barbell row" },

  // Shoulders
  { name: "Standing Overhead Press", muscleGroup: "Shoulders", targetNotes: "Anterior deltoid", dataAiHint: "overhead press" },
  { name: "Dumbbell Overhead Press", muscleGroup: "Shoulders", targetNotes: "Anterior deltoid", dataAiHint: "dumbbell press" },
  { name: "Machine Shoulder Press", muscleGroup: "Shoulders", targetNotes: "Anterior deltoid", dataAiHint: "shoulder machine" },
  { name: "Lateral Raise Machine", muscleGroup: "Shoulders", targetNotes: "Lateral deltoid", dataAiHint: "lateral raise machine" },
  { name: "Lateral Raise Dumbbell", muscleGroup: "Shoulders", targetNotes: "Lateral deltoid", dataAiHint: "dumbbell raise" },
  { name: "Cable Lateral Raise", muscleGroup: "Shoulders", targetNotes: "Lateral deltoid", dataAiHint: "cable raise" },
  { name: "Reverse Peck Deck", muscleGroup: "Shoulders", targetNotes: "Posterior deltoid", dataAiHint: "reverse fly machine" },
  { name: "Seated Reverse Dumbbell Flye", muscleGroup: "Shoulders", targetNotes: "Posterior deltoid", dataAiHint: "dumbbell fly" },

  // Legs
  { name: "Barbell Back Squat", muscleGroup: "Legs", targetNotes: "Quadriceps, glutes, hamstrings", dataAiHint: "barbell squat" },
  { name: "Hack Squat", muscleGroup: "Legs", targetNotes: "Quadriceps", dataAiHint: "hack squat" },
  { name: "Leg Extension", muscleGroup: "Legs", targetNotes: "Quadriceps", dataAiHint: "leg extension machine" },
  { name: "Leg Press Machine", muscleGroup: "Legs", targetNotes: "Quadriceps, glutes", dataAiHint: "leg press machine" },
  { name: "Leg Curl Machine", muscleGroup: "Legs", targetNotes: "Hamstrings", dataAiHint: "leg curl machine" },
  { name: "Romanian Dead Lift", muscleGroup: "Legs", targetNotes: "Hamstrings, glutes", dataAiHint: "romanian deadlift" },
  { name: "Hip Thrust", muscleGroup: "Legs", targetNotes: "Glutes", dataAiHint: "hip thrust exercise" },
  { name: "Abductor Machine", muscleGroup: "Legs", targetNotes: "Glutes", dataAiHint: "abductor machine" },
  { name: "Standing Calves", muscleGroup: "Legs", targetNotes: "Gastrocnemius", dataAiHint: "calf raise" },

  // Triceps
  { name: "Dips (Triceps Focus)", muscleGroup: "Triceps", targetNotes: "Lateral head", dataAiHint: "tricep dips" },
  { name: "Cable Triceps Kickback", muscleGroup: "Triceps", targetNotes: "Lateral head", dataAiHint: "tricep kickback" },
  { name: "Overhead Cable Triceps Extension", muscleGroup: "Triceps", targetNotes: "Long head", dataAiHint: "tricep extension cable" },
  { name: "Skullcrusher", muscleGroup: "Triceps", targetNotes: "Long head", dataAiHint: "skullcrusher exercise" },

  // Biceps
  { name: "EZ Bar Curl", muscleGroup: "Biceps", targetNotes: "Short Head-Inner", dataAiHint: "ez bar curl" },
  { name: "Chinup", muscleGroup: "Biceps", targetNotes: "Short-Inner and Long-Outer", dataAiHint: "chin up" },
  { name: "Incline Dumbbell Curl", muscleGroup: "Biceps", targetNotes: "Long Head-Outer", dataAiHint: "incline curl" },
  { name: "Face Away Bayesian Cable Curl", muscleGroup: "Biceps", targetNotes: "Long Head-Outer", dataAiHint: "cable curl" },
  { name: "Hammer Curl", muscleGroup: "Biceps", targetNotes: "Brachialis", dataAiHint: "hammer curl" },

  // Abs
  { name: "Cable Crunch", muscleGroup: "Abs", targetNotes: "Upper", dataAiHint: "cable crunch abs" },
  { name: "Crunch Machine", muscleGroup: "Abs", targetNotes: "Upper", dataAiHint: "abs machine" },
  { name: "Candlestick", muscleGroup: "Abs", targetNotes: "Upper & Lower", dataAiHint: "candlestick abs" },
  { name: "Hanging Leg Raise", muscleGroup: "Abs", targetNotes: "Lower", dataAiHint: "leg raise hanging" },
  { name: "Back-Supported Leg Raise", muscleGroup: "Abs", targetNotes: "Lower", dataAiHint: "leg raise support" },
  { name: "Super Range Motion Crunch", muscleGroup: "Abs", targetNotes: "Upper & Lower", dataAiHint: "abs crunch" },
  { name: "Abs Wheel/Rollout", muscleGroup: "Abs", targetNotes: "Core Stability", dataAiHint: "ab wheel" },
  
  // Other (Example, can be expanded)
  { name: "Foam Rolling", muscleGroup: "Other", targetNotes: "Myofascial release", dataAiHint: "foam roller" },
  { name: "Stretching", muscleGroup: "Other", targetNotes: "General flexibility", dataAiHint: "stretching fitness" },
];
